nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
    ports:
        - "80:80"

node1:
    build: ./AppServers/AppServer1
    links:
        - mongodb
    ports:
        - "5000"

node2:
    build: ./AppServers/AppServer2
    links:
        - mongodb
    ports:
        - "5001"

mongodb:
  image: mongo:3.4.0
  ports:
    - "27017:27017"


